-- ==========================================
-- EXTENSIONS
-- ==========================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;

-- ==========================================
-- CLEANUP
-- ==========================================

DROP TABLE IF EXISTS public.remediation_exercises CASCADE;
DROP TABLE IF EXISTS public.student_weak_concepts CASCADE;
DROP TABLE IF EXISTS public.concept_dependencies CASCADE;
DROP TABLE IF EXISTS public.concepts CASCADE;
DROP TABLE IF EXISTS public.teacher_reviews CASCADE;
DROP TABLE IF EXISTS public.grading_jobs CASCADE;
DROP TABLE IF EXISTS public.knowledge_embeddings CASCADE;
DROP TABLE IF EXISTS public.knowledge_documents CASCADE;
DROP TABLE IF EXISTS public.teacher_solutions CASCADE;

DROP TABLE IF EXISTS public.ai_student_report_cards CASCADE;
DROP TABLE IF EXISTS public.ai_evaluations CASCADE;
DROP TABLE IF EXISTS public.student_answers CASCADE;
DROP TABLE IF EXISTS public.ai_student_answers CASCADE;
DROP TABLE IF EXISTS public.rubrics CASCADE;
DROP TABLE IF EXISTS public.questions CASCADE;
DROP TABLE IF EXISTS public.ai_grading_criteria CASCADE;
DROP TABLE IF EXISTS public.assignments CASCADE;
DROP TABLE IF EXISTS public.students CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- ==========================================
-- 1. BASE AUTH & USERS
-- ==========================================

CREATE TABLE IF NOT EXISTS public.users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  display_name text,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.students (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  student_id text NOT NULL,
  name text NOT NULL,

  created_at timestamp with time zone NOT NULL DEFAULT now(),

  CONSTRAINT students_teacher_uuid_unique UNIQUE (teacher_id, id),
  CONSTRAINT students_teacher_student_id_unique UNIQUE (teacher_id, student_id),

  CONSTRAINT students_teacher_id_fkey
    FOREIGN KEY (teacher_id)
    REFERENCES public.users(id)
);

-- ==========================================
-- 2. ASSIGNMENTS
-- ==========================================

CREATE TABLE public.assignments (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  teacher_id uuid NOT NULL,
  title text NOT NULL,
  subject text,
  total_marks integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT assignments_pkey PRIMARY KEY (id),
  CONSTRAINT assignments_teacher_id_fkey 
    FOREIGN KEY (teacher_id) 
    REFERENCES public.users(id)
);

-- ==========================================
-- 3. QUESTIONS
-- ==========================================

CREATE TABLE public.questions (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  teacher_id uuid NOT NULL,
  assignment_id integer NOT NULL,

  question_label text NOT NULL,
  question_description text NOT NULL,

  marks integer,

  created_at timestamp with time zone DEFAULT now(),

  CONSTRAINT questions_pkey PRIMARY KEY (id),

  CONSTRAINT questions_teacher_fkey
    FOREIGN KEY (teacher_id)
    REFERENCES public.users(id),

  CONSTRAINT questions_assignment_fkey
    FOREIGN KEY (assignment_id)
    REFERENCES public.assignments(id)
);

-- ==========================================
-- 4. RUBRICS
-- ==========================================

CREATE TABLE public.rubrics (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  teacher_id uuid NOT NULL,
  assignment_id integer NOT NULL,

  question_label text NOT NULL,

  rubric_description jsonb NOT NULL,

  created_at timestamp with time zone DEFAULT now(),

  CONSTRAINT rubrics_pkey PRIMARY KEY (id),

  CONSTRAINT rubrics_teacher_fkey
    FOREIGN KEY (teacher_id)
    REFERENCES public.users(id),

  CONSTRAINT rubrics_assignment_fkey
    FOREIGN KEY (assignment_id)
    REFERENCES public.assignments(id)
);

-- ==========================================
-- 5. TEACHER SOLUTIONS
-- ==========================================

CREATE TABLE public.teacher_solutions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  teacher_id uuid NOT NULL,
  assignment_id integer NOT NULL,

  question_label text NOT NULL,

  solution_text text NOT NULL,

  created_at timestamp with time zone DEFAULT now(),

  CONSTRAINT teacher_solutions_teacher_fkey
    FOREIGN KEY (teacher_id)
    REFERENCES public.users(id),

  CONSTRAINT teacher_solutions_assignment_fkey
    FOREIGN KEY (assignment_id)
    REFERENCES public.assignments(id)
);

-- ==========================================
-- 6. STUDENT ANSWERS
-- ==========================================

CREATE TABLE public.student_answers (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  teacher_id uuid NOT NULL,
  student_id uuid NOT NULL,

  assignment_id integer NOT NULL,

  question_label text NOT NULL,

  answer text NOT NULL,

  created_at timestamp with time zone DEFAULT now(),

  CONSTRAINT student_answers_pkey PRIMARY KEY (id),

  CONSTRAINT student_answers_assignment_fkey
    FOREIGN KEY (assignment_id)
    REFERENCES public.assignments(id),

  CONSTRAINT student_answers_student_fkey
    FOREIGN KEY (teacher_id, student_id)
    REFERENCES public.students(teacher_id, id)
);

-- ==========================================
-- 7. AI EVALUATIONS
-- ==========================================

CREATE TABLE public.ai_evaluations (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  student_answer_id integer NOT NULL,

  final_score numeric,

  final_feedback text,

  detailed_marks jsonb NOT NULL,

  confidence_score numeric,

  evaluation_metadata jsonb,

  evaluated_at timestamp with time zone NOT NULL DEFAULT now(),

  CONSTRAINT ai_evaluations_pkey PRIMARY KEY (id),

  CONSTRAINT ai_evaluations_answer_fkey
    FOREIGN KEY (student_answer_id)
    REFERENCES public.student_answers(id)
);

-- ==========================================
-- 8. TEACHER REVIEWS
-- ==========================================

CREATE TABLE public.teacher_reviews (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  evaluation_id integer NOT NULL,

  teacher_score numeric,

  teacher_feedback text,

  approved boolean DEFAULT false,

  reviewed_at timestamp with time zone DEFAULT now(),

  CONSTRAINT teacher_reviews_evaluation_fkey
    FOREIGN KEY (evaluation_id)
    REFERENCES public.ai_evaluations(id)
);

-- ==========================================
-- 9. KNOWLEDGE DOCUMENTS (RAG)
-- ==========================================

CREATE TABLE public.knowledge_documents (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  teacher_id uuid NOT NULL,

  subject text NOT NULL,
  topic text NOT NULL,

  document_type text NOT NULL,

  file_name text,

  content text NOT NULL,

  created_at timestamp with time zone DEFAULT now(),

  CONSTRAINT knowledge_documents_teacher_fkey
    FOREIGN KEY (teacher_id)
    REFERENCES public.users(id)
);

-- ==========================================
-- 10. KNOWLEDGE EMBEDDINGS
-- ==========================================

CREATE TABLE public.knowledge_embeddings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  document_id integer NOT NULL,

  chunk_text text NOT NULL,

  embedding vector(1536),

  created_at timestamp with time zone DEFAULT now(),

  CONSTRAINT knowledge_embeddings_document_fkey
    FOREIGN KEY (document_id)
    REFERENCES public.knowledge_documents(id)
);

-- ==========================================
-- 11. GRADING JOBS
-- ==========================================

CREATE TABLE public.grading_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  teacher_id uuid NOT NULL,

  assignment_id integer NOT NULL,

  student_id uuid NOT NULL,

  status text NOT NULL DEFAULT 'queued',

  created_at timestamp with time zone DEFAULT now(),

  completed_at timestamp with time zone,

  CONSTRAINT grading_jobs_assignment_fkey
    FOREIGN KEY (assignment_id)
    REFERENCES public.assignments(id),
    
  CONSTRAINT grading_jobs_teacher_fkey
    FOREIGN KEY (teacher_id)
    REFERENCES public.users(id),

  CONSTRAINT grading_jobs_student_fkey
    FOREIGN KEY (teacher_id, student_id)
    REFERENCES public.students(teacher_id, id)
);

-- ==========================================
-- 12. CONCEPTS (GRAPH RAG)
-- ==========================================

CREATE TABLE public.concepts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  subject text NOT NULL,

  name text NOT NULL UNIQUE,

  description text
);

-- ==========================================
-- 13. CONCEPT DEPENDENCIES
-- ==========================================

CREATE TABLE public.concept_dependencies (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  concept_id integer NOT NULL,

  prerequisite_concept_id integer NOT NULL,

  CONSTRAINT concept_dependencies_concept_fkey
    FOREIGN KEY (concept_id)
    REFERENCES public.concepts(id),

  CONSTRAINT concept_dependencies_prereq_fkey
    FOREIGN KEY (prerequisite_concept_id)
    REFERENCES public.concepts(id)
);

-- ==========================================
-- 14. STUDENT WEAK CONCEPTS
-- ==========================================

CREATE TABLE public.student_weak_concepts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  teacher_id uuid NOT NULL,

  student_id uuid NOT NULL,

  concept_id integer NOT NULL,

  weakness_score numeric,

  created_at timestamp with time zone DEFAULT now(),

  CONSTRAINT weak_concepts_concept_fkey
    FOREIGN KEY (concept_id)
    REFERENCES public.concepts(id),
    
  CONSTRAINT weak_concepts_teacher_fkey
    FOREIGN KEY (teacher_id)
    REFERENCES public.users(id),

  CONSTRAINT student_weak_concepts_student_fkey
    FOREIGN KEY (teacher_id, student_id)
    REFERENCES public.students(teacher_id, id)
);

-- ==========================================
-- 15. REMEDIATION EXERCISES
-- ==========================================

CREATE TABLE public.remediation_exercises (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  student_id uuid NOT NULL,

  concept_id integer NOT NULL,

  generated_question text NOT NULL,

  difficulty text,

  created_at timestamp with time zone DEFAULT now(),

  CONSTRAINT remediation_exercises_student_fkey
    FOREIGN KEY (student_id)
    REFERENCES public.students(id)
);

-- ==========================================
-- INDEXES
-- ==========================================

CREATE INDEX idx_questions_assignment
ON public.questions(assignment_id);

CREATE INDEX idx_rubrics_assignment
ON public.rubrics(assignment_id);

CREATE UNIQUE INDEX rubrics_teacher_assignment_question_label_unique
ON public.rubrics (
  teacher_id,
  assignment_id,
  regexp_replace(lower(question_label), '\s+', '', 'g')
);

CREATE INDEX idx_student_answers_assignment
ON public.student_answers(assignment_id);

CREATE INDEX idx_student_answers_student
ON public.student_answers(student_id);

CREATE INDEX idx_ai_evaluations_answer
ON public.ai_evaluations(student_answer_id);

CREATE INDEX idx_knowledge_embeddings_document
ON public.knowledge_embeddings(document_id);

CREATE INDEX idx_concept_dependencies_concept
ON public.concept_dependencies(concept_id);

CREATE INDEX idx_student_weak_concepts_student
ON public.student_weak_concepts(student_id);

-- ==========================================
-- OPTIONAL VECTOR INDEX (FOR RAG SEARCH)
-- ==========================================

CREATE INDEX knowledge_embedding_idx
ON public.knowledge_embeddings
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- 1. Syllabus uploads (scoped per assignment)
CREATE TABLE public.syllabi (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id uuid NOT NULL,
  assignment_id integer NOT NULL,
  filename text NOT NULL,
  raw_text text,
  status text NOT NULL DEFAULT 'processing',
  entity_count integer DEFAULT 0,
  relationship_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT syllabi_teacher_fkey FOREIGN KEY (teacher_id) REFERENCES public.users(id),
  CONSTRAINT syllabi_assignment_fkey FOREIGN KEY (assignment_id) REFERENCES public.assignments(id) ON DELETE CASCADE,
  CONSTRAINT unique_syllabus_per_assignment UNIQUE (assignment_id)
);

-- 2. Entities extracted from syllabus (with vector embedding)
CREATE TABLE public.syllabus_entities (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  syllabus_id integer NOT NULL,
  name text NOT NULL,
  entity_type text NOT NULL,
  description text,
  difficulty_level text,
  week_or_unit text,
  embedding vector(1536),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT entities_syllabus_fkey FOREIGN KEY (syllabus_id) REFERENCES public.syllabi(id) ON DELETE CASCADE,
  CONSTRAINT unique_entity_per_syllabus UNIQUE (syllabus_id, name)
);

-- 3. Relationships between entities
CREATE TABLE public.syllabus_relationships (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  syllabus_id integer NOT NULL,
  source_entity_id integer NOT NULL,
  target_entity_id integer NOT NULL,
  relationship_type text NOT NULL,
  strength integer DEFAULT 3,
  reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rel_syllabus_fkey FOREIGN KEY (syllabus_id) REFERENCES public.syllabi(id) ON DELETE CASCADE,
  CONSTRAINT rel_source_fkey FOREIGN KEY (source_entity_id) REFERENCES public.syllabus_entities(id) ON DELETE CASCADE,
  CONSTRAINT rel_target_fkey FOREIGN KEY (target_entity_id) REFERENCES public.syllabus_entities(id) ON DELETE CASCADE
);

-- Indexes
CREATE INDEX idx_entities_syllabus ON public.syllabus_entities(syllabus_id);
CREATE INDEX idx_entities_embedding ON public.syllabus_entities USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
CREATE INDEX idx_relationships_syllabus ON public.syllabus_relationships(syllabus_id);
CREATE INDEX idx_relationships_source ON public.syllabus_relationships(source_entity_id);
CREATE INDEX idx_relationships_target ON public.syllabus_relationships(target_entity_id);
